if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }

__d("CometSinglePostContentQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5563266207021193"}),null);
__d("CometSinglePostContentQuery$Parameters",["CometSinglePostContentQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometSinglePostContentQuery_facebookRelayOperation"),metadata:{},name:"CometSinglePostContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("ProfileCometTimelineListViewRootQuery$Parameters",["ProfileCometTimelineListViewRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometTimelineListViewRootQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometTimelineListViewRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("ProfileCometHeaderQuery$Parameters",["ProfileCometHeaderQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometHeaderQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometHeaderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("ProfileCometTimelineFeedQuery$Parameters",["ProfileCometTimelineFeedQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometTimelineFeedQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometTimelineFeedQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("ProfileCometViewAsBarQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4077637725659241"}),null);
__d("ProfileCometViewAsBarQuery$Parameters",["ProfileCometViewAsBarQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometViewAsBarQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometViewAsBarQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometProfileLoggedOutCTAWrapperFooterDataQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5341536295888250"}),null);
__d("CometProfileLoggedOutCTAWrapperFooterDataQuery$Parameters",["CometProfileLoggedOutCTAWrapperFooterDataQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometProfileLoggedOutCTAWrapperFooterDataQuery_facebookRelayOperation"),metadata:{},name:"CometProfileLoggedOutCTAWrapperFooterDataQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometSinglePostRoot.entrypoint",["CometSinglePostContentQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){var c=a.routeParams,e=c.comment_id;c=c.reply_comment_id;a=a.routeProps.storyID;c=(c=c)!=null?c:e;e={UFI2CommentsProvider_commentsKey:"CometSinglePostRoute",displayCommentsContextEnableComment:null,displayCommentsContextIsAdPreview:null,displayCommentsContextIsAggregatedShare:null,displayCommentsContextIsStorySet:null,displayCommentsFeedbackContext:null,feedbackSource:2,feedLocation:"PERMALINK",focusCommentID:c!=null?String(c):null,privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"permalink",scale:d("WebPixelRatio").get(),storyID:a,useDefaultActor:!1};c={singlePostRootQueryReference:{environmentProviderOptions:{ssrBoundary:"feed"},parameters:b("CometSinglePostContentQuery$Parameters"),variables:e}};return{queries:c}},root:c("JSResourceForInteraction")("CometSinglePostRoot.react").__setRef("CometSinglePostRoot.entrypoint")};g["default"]=a}),98);
__d("ProfileCometViewAsBar.entrypoint",["JSResourceForInteraction","ProfileCometViewAsBarQuery$Parameters"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.profileID;return{queries:{queryReference:{parameters:c("ProfileCometViewAsBarQuery$Parameters"),variables:{id:a}}}}},root:c("JSResourceForInteraction")("ProfileCometViewAsBar.react").__setRef("ProfileCometViewAsBar.entrypoint")};g["default"]=a}),98);
__d("buildCometProfileRoute.entrypoint",["CometProfileLoggedOutCTAWrapperFooterDataQuery$Parameters","JSResourceForInteraction","ProfileCometHeaderQuery$Parameters","ProfileCometViewAsBar.entrypoint","ProfileCometViewAsConstants.entrypoint","WebPixelRatio","createGenericCompoundEntryPointBuilder","gkx","qex"],(function(a,b,c,d,e,f,g){"use strict";function a(a,b){var e=c("createGenericCompoundEntryPointBuilder")(a,b);return function(a,b){var f={getPreloadProps:b,root:a};return e(function(a){return a.routeProps.viewerID===d("ProfileCometViewAsConstants.entrypoint").VIEW_AS_EVERYONE_USER?{contentEntryPoint:{entryPoint:f,entryPointParams:a},viewAsEntryPoint:{entryPoint:c("ProfileCometViewAsBar.entrypoint"),entryPointParams:{profileID:a.routeProps.userID}}}:{contentEntryPoint:{entryPoint:f,entryPointParams:a}}})}}b=a(c("JSResourceForInteraction")("ProfileCometRoot.react").__setRef("buildCometProfileRoute.entrypoint"),function(a){var b,e,f=a.routeProps,g=f.groupID;f=f.userID;var h=g===null?"profile":"community";b=(b=c("qex")._("1479"))!=null?b:!1;a=a.routeProps.userID===a.routeProps.viewerID;h={environmentProviderOptions:{ssrBoundary:"root"},parameters:c("ProfileCometHeaderQuery$Parameters"),variables:{scale:d("WebPixelRatio").get(),selectedID:(e=g)!=null?e:f,selectedSpaceType:h,selectedTab:g!=null?String(g):String(f),shouldUseFXIMProfilePicEditor:a&&((e=c("qex")._("967"))!=null?e:!1),showBioInVNextHeader:b,userID:String(f)}};if(c("gkx")("1801408"))return{footerDataQueryReference:{parameters:c("CometProfileLoggedOutCTAWrapperFooterDataQuery$Parameters"),variables:{height:500,scale:d("WebPixelRatio").get(),userID:String(f),width:500}},headerQueryReference:h};else return{headerQueryReference:h}});g["default"]=b}),98);
__d("ProfileCometTimelineListViewRouteRoot.entrypoint",["JSResourceForInteraction","ProfileCometTimelineFeedQuery$Parameters","ProfileCometTimelineListViewRootQuery$Parameters","WebPixelRatio","buildCometProfileRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildCometProfileRoute.entrypoint")(c("JSResourceForInteraction")("ProfileCometTimelineListViewRoot.react").__setRef("ProfileCometTimelineListViewRouteRoot.entrypoint"),function(a){var b=1;b={UFI2CommentsProvider_commentsKey:"ProfileCometTimelineRoute",count:b,feedbackSource:0,feedLocation:"TIMELINE",omitPinnedPost:!0,privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"timeline",scale:d("WebPixelRatio").get(),userID:String(a.routeProps.userID)||""};a.routeProps.hasMentionsTab===!0&&(b=babelHelpers["extends"]({},b,{postedBy:{group:"OWNER"}}));return{queries:{timelineFeedQueryReference:{environmentProviderOptions:{ssrBoundary:"root"},parameters:c("ProfileCometTimelineFeedQuery$Parameters"),variables:b},timelineListViewRootQueryReference:{environmentProviderOptions:{ssrBoundary:"root"},parameters:c("ProfileCometTimelineListViewRootQuery$Parameters"),variables:{scale:d("WebPixelRatio").get(),userID:String(a.routeProps.userID)||""}}}}});g["default"]=a}),98);